### PR TITLE
chore(ci): Add ci tests

### LINKED ISSUE #4: add CI integration for examples

### PR DESCRIPTION
**Pull request by aniketbiswas21**
# Issue Related with PR
- fixes #4 

# Proposed Changes
- Added CI tests for sample apps

# Additional info if necessary
- Also added the missing packages in the typescript app
- There are a couple of failing tests in the application. Will raise an issue for the same(#11)

# Checklist
- [x] Added CI Checks
- [x] Fix missing packages in typescript app

### CODE REVIEW

**Comment by aniketbiswas21** [comment]
@YashKumarVerma Please take a look!

**Comment by aniketbiswas21** [comment]
@YashKumarVerma As discussed earlier, for the ci checks to be run on a forked repo's branch. Some additional configuration needs to be done in the repository settings.

**Comment by aniketbiswas21** [comment]
@YashKumarVerma Please review this too!

**Review by YashKumarVerma — APPROVED** [review]

**Comment by YashKumarVerma** [comment]
thanks !

**Pull request merged**
